language: csharp
solution: LuceneQueryBuilder.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore LuceneQueryBuilder.sln
after_script:
  - nunit-console LuceneQueryBuilder.Test/bin/Release/Tests.dll
